export const initialData = [
  {
    "_Locked": false,
    "_Players": 1,
    "Vex Rune": 2,
    "Ohm Rune": 4,
    "Lo Rune": 3,
    "Sur Rune": 2,
    "Ber Rune": 1,
    "Pul Rune": 9,
    "Mal Rune": 9,
    "Ist Rune": 4,
    "Um Rune": 8,
    "Gul Rune": 6
  },
  {
    "_Locked": true,
    "_Players": 1,
    "Vex Rune": 2,
    "Ohm Rune": 4,
    "Lo Rune": 3,
    "Sur Rune": 3,
    "Ber Rune": 1,
    "Pul Rune": 9,
    "Mal Rune": 9,
    "Ist Rune": 5,
    "Um Rune": 8,
    "Gul Rune": 6
  },
  {
    "_Locked": false,
    "_Players": 3,
    "Vex Rune": 3,
    "Ohm Rune": 2,
    "Lo Rune": 4,
    "Sur Rune": 4,
    "Ber Rune": 2,
    "Pul Rune": 12,
    "Mal Rune": 12,
    "Ist Rune": 8,
    "Um Rune": 7,
    "Gul Rune": 4
  },
  {
    "_Locked": true,
    "_Players": 3,
    "Vex Rune": 3,
    "Ohm Rune": 2,
    "Lo Rune": 4,
    "Sur Rune": 5,
    "Ber Rune": 2,
    "Pul Rune": 14,
    "Mal Rune": 12,
    "Ist Rune": 10,
    "Um Rune": 9,
    "Gul Rune": 6
  },
  {
    "_Locked": false,
    "_Players": 5,
    "Vex Rune": 6,
    "Ohm Rune": 2,
    "Lo Rune": 4,
    "Sur Rune": 5,
    "Ber Rune": 4,
    "Pul Rune": 16,
    "Mal Rune": 10,
    "Ist Rune": 5,
    "Um Rune": 11,
    "Gul Rune": 5
  },
  {
    "_Locked": true,
    "_Players": 5,
    "Vex Rune": 6,
    "Ohm Rune": 2,
    "Lo Rune": 4,
    "Sur Rune": 7,
    "Ber Rune": 4,
    "Pul Rune": 18,
    "Mal Rune": 10,
    "Ist Rune": 6,
    "Um Rune": 11,
    "Gul Rune": 5
  },
  {
    "_Locked": false,
    "_Players": 7,
    "Vex Rune": 6,
    "Ohm Rune": 5,
    "Lo Rune": 2,
    "Sur Rune": 9,
    "Ber Rune": 2,
    "Pul Rune": 16,
    "Mal Rune": 14,
    "Ist Rune": 5,
    "Um Rune": 10,
    "Gul Rune": 11
  },
  {
    "_Locked": true,
    "_Players": 7,
    "Vex Rune": 6,
    "Ohm Rune": 5,
    "Lo Rune": 2,
    "Sur Rune": 9,
    "Ber Rune": 2,
    "Pul Rune": 16,
    "Mal Rune": 15,
    "Ist Rune": 7,
    "Um Rune": 11,
    "Gul Rune": 11
  }
]
